spring:
  application:
    name: whats-for-dinner
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://localhost:9411}

server:
  port: ${PORT:8181}

management:
    port: 9181

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:${spring.cloud.client.ipAddress}}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
